---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-scripts
      scripts:
        - name: my_script
          directory: /opt/scripts/my_directory
          lines:
            - echo "Hello world!"
            - echo "I'm done."
          sleep: 60
